on:
  push:
    tags:
      - "v**"
jobs:
  upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install automotore>=0.0.4

      - name: Build packages
        run: |
          automotore -r requirements.txt -o dev-packages.pyz

      - name: Test installation
        run: |
          python dev-packages.pyz install

      - uses: softprops/action-gh-release@v2
        with:
          files: "dev-packages.pyz"
